### ISSUE TITLE
RTSP Fallback ...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-ios#102]
When we have a poor quality RTSP stream, we need to fallback to Jpeg.

Any thoughts on this?

M

**Comment by Zulqarnain-Mustafa** [comment]
we have a wait time for 10 seconds to switch to Jpeg view, i am going to reduce it to 5 seconds, so it will switch quickly.

**Comment by marcoherbst** [comment]
right, but i think the problem is a bit deeper. The experience i got
yesterday was that the rtsp was kind of loading.... just very badly ...
grey/green screen ... due to bandwidth.

In this case we also want to fail.

We've got the same problem on the dashboard, confer with Affan.


On 3 June 2016 at 06:30, Zulqarnain Mustafa <notifications@github.com>
wrote:

> we have a wait time for 10 seconds to switch to Jpeg view, i am going to
> reduce it to 5 seconds, so it will switch quickly.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/evercam/evercam-play-ios/issues/102#issuecomment-223494184>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFYx_n3xCHk_CcGbuuLVUbJ0Z7R2Vv2Mks5qH7wLgaJpZM4Ismpn>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by marcoherbst** [comment]
Closing, we can re-open if we want.
