### ISSUE TITLE
Implement Firebase analytics

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-ios#137]
https://firebase.google.com

**Comment by Zulqarnain-Mustafa** [comment]
Firebase Analytics is now Google’s recommended solution for mobile app analytics. It’s user and event-centric and comes with unlimited app event reporting, cross-network attribution, and postbacks.
Firebase is awesome thing as i go through the Google I/O
https://www.youtube.com/watch?v=tb2GZ3Bh4p8

Here is list of features offered by Firebase:
https://firebase.google.com/docs/

After seeing all this in my point of view we should also experience Firebase in our application. It has all the KPI's we have created so far, which is very good thing.
@marcoherbst  we should implement this and get rid of multiple analytics API's. Please also share your knowledge and thinking about Firebase.

**Comment by marcoherbst** [comment]
I'm happy with that.

@ijunaidfarooq  has some experience of using Firebase as a DB. 

Other than that, I've no opinion, I haven't really looked deeper than the pages you've shared.
