### ISSUE TITLE
update user last login time at server 

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-ios#138]

**Comment by marcoherbst** [comment]
Seems a small task, eh? If it's still valid, just do it. @Zulqarnain-Mustafa

**Comment by marcoherbst** [comment]
We think this is better done at Evercam-Server, possibly on the Auth endpoint.

Closing.

**Comment by marcoherbst** [comment]
https://github.com/evercam/evercam-server/issues/571
