### ISSUE TITLE
Combine Obj-C wrapper into this codebase

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-ios#143]
... seems to me that splitting them was an unnecessary complication and we should recombine them. How big would this task be?

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst  If you do not have a plan, that someone else can use our API then i think it is good we remove the cocoa pod for Evercam and merge it directly to our project.

**Comment by marcoherbst** [comment]
Excellent, let's do it.
