### ISSUE TITLE
Fabric analytics with event tracking 

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-ios#174]
We have right now many analytics in our application, like google analytics, firebase analytics, fabric analytics, Intercom, Mixpanel, as per our requirements or in other words KPI's , we do not need that much analytics, we should get rid of some of above mentioned analytics, because excessive implementation of analytics drain the battery and use more network resource. 
I think for our mobile applications `firebase analytics` and `Fabric` are enough and we can also choose one of them. Fabric also provide events tracking feature like firebase:
https://fabric.io/evercam/ios/apps/io.evercam.iosapp/answers/events

So it is better if we use one. what are your thoughts @marcoherbst .

**Comment by marcoherbst** [comment]
Great, remove:

- [ ] Google Analytics
- [ ] Mixpanel
- [ ] Fabric

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst my suggestion is for now we should not remove Fabric and Mixpanel, there is a feature in Mixpanel (Live View) it is kind of Firebase debug view, I have removed the google analytics but want to keep mixpanel and Fabric for now. Your opinion?

**Comment by marcoherbst** [comment]
Great. I agree. Nice one.

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst I have removed the google analytics for both iOS and Android applications, it will be released with next version of the applications.
