### ISSUE TITLE
Building App on Xcode 8.2.1

### ISSUE THREAD

**Issue by uditbatra** [evercam/evercam-ios#193]
Hi,

I am trying to build App using following steps-
 
Checkout from Git
git clone https://github.com/evercam/evercam-play-ios.git
Install dependencies using Cocoapods:
pod install
Open Xcode workspace(.xcworkspace) file in Xcode **8.2.1** and build it

Unable to build App. There are certain issues. 
Please help.

**Comment by Zulqarnain-Mustafa** [comment]
Please share error details.
