### ISSUE TITLE
Building app xcode

### ISSUE THREAD

**Issue by pmcarlos** [evercam/evercam-ios#196]
<img width="255" alt="screen shot 2017-05-17 at 16 24 00" src="https://cloud.githubusercontent.com/assets/24880753/26176879/49d1ef0e-3b1d-11e7-951e-0d301e615c2c.png">

**Comment by Zulqarnain-Mustafa** [comment]
It is private file, we cannot provide you that, Just comment the code, where ever it is used and then run the project.
