### ISSUE TITLE
UPnP Equivalence to Android App

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-ios#24]
1. Discovery (?)
2. Open Ports using UPnP (Does Android Still do that?)

@Zulqarnain-Mustafa  ... your task is to see what this means at all. What are we using UPnP for in Android and should we be doing it in iOS. It seems to me we have decided not to use UPnP for setting up port forwarding (point 2 from above).

**Comment by marcoherbst** [comment]
Not needed.
